sudo: false
language: node_js
node_js:
  - '10'
before_install:
services:
  - redis-server
install:
  - npm install
before_script:
  - npm i -g sails@1.0.2
  - npm i @gmod/jbrowse@1.15.1
  - node ./utils/jb_setup.js
script:
  - npm run coverage
after_success:
  - ls coverage 
  - npm run coveralls
after_failure:
  - cat node_modules/@gmod/jbrowse/setup.log 
