sudo: false
language: node_js
node_js:
  - '10'
before_install:
services:
  - redis-server
install:
  - npm install
before_script:
  - npm i -g sails@1.0.2
script:
  - npm install gmod/jbrowse#jbconnectdemo
#  - npm install @gmod/jbrowse@1.15.1
#  - patch node_modules/@gmod/jbrowse/setup.sh fix_jbrowse_setup.patch
  - cat node_modules/@gmod/jbrowse/package.json
  - ./utils/jb_setup.js
  - git clone https://github.com/primer3-org/primer3.git primer3
  - cd primer3/src
  - make
  - cd ../..
  - npm run coverage
after_success:
  - ls coverage 
  - npm run coveralls
  - ./node_modules/nyc/bin/nyc.js report
after_failure:
  - cat node_modules/@gmod/jbrowse/setup.log 
