sudo: false
language: node-js
before_install:
services:
  - redis-server
install:
  - npm install
before_script:
  - npm i -g sails@1.0.2
  - npm i @gmod/jbrowse@1.15.1
  - node ./utils/jb_setup.js
script:
  - npm run test-coverage
after_failure:
  - cat node_modules/@gmod/jbrowse/setup.log 

