#!/usr/bin/env node

var sh = require('shelljs');
var getopt = require('node-getopt');
var jblib = require('./api/services/jbutillib');


var subCount = 0;

initFunctions();

var mergedConfig = jblib.getMergedConfig();

// local options
var options = [
    ['c','config', 'display merged configuration']
    //['','testsetupindex','testsetupinex']
];

// add jbconnect-hook-* hook options
jblib.doExtScripts(function(ext,path) {
    options = options.concat(ext.getOptions());
});

// help
options = options.concat([
    ['h','help', 'display this help']
]);

var getopt = new getopt(options);

getopt.bindHelp();     // bind option 'help' to default action
opt = getopt.parseSystem(); // parse command line

var helpTxt = 
    "Usage: jbutil [OPTION]\n" +
    "[[OPTIONS]]\n" +
    "\n";

jblib.doExtScripts(function(ext) {
    helpTxt += ext.getHelpText();
});

getopt.setHelp(helpTxt);


/* Display help if no arguments are passed */
if (!process.argv.slice(2).length) {
	getopt.showHelp();
	process.exit(1);
}

/************************************************
 * process commands
 ************************************************/

 // process commands for hook modules
jblib.doExtScripts(function(ext,path) {
    ext.process(opt,path,mergedConfig);
});

if (opt.options['config']) proc_Config();  

// --config - list config
function proc_Config() {

    console.log('Merged jbrowse configs from config/globals.js:');
    console.log( mergedConfig );
}

/************************************************
 * Utility functions
 ************************************************/
function initFunctions() {
}

    